name: deploy siap-penus

on: 
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: siap-penus
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /www/wwwroot/siap-penus
            git pull origin main
            ~/.bun/bin/bun run build
            npx pm2 restart siap-penus